services:
    php:
        build:
            context: ./docker/php
        container_name: ${PROJECT_NAME}_php
        env_file:
            - .env
        volumes:
            - ./app:/var/www/html
        working_dir: /var/www/html
        networks:
            - ${PROJECT_NAME}_network
        depends_on:
            - database
    nginx:
        image: nginx:alpine
        container_name: ${PROJECT_NAME}_nginx
        volumes:
            - ./app:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8090:80"
        depends_on:
            - php
        networks:
            - ${PROJECT_NAME}_network
    database:
        image: mariadb:10.11
        container_name: ${PROJECT_NAME}_mariadb
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
        volumes:
            - mariadb_data:/var/lib/mysql
        ports:
            - "3366:3306"
        networks:
            - ${PROJECT_NAME}_network
        restart: always
        env_file:
            - .env

volumes:
    mariadb_data:

networks:
    application_network:
        driver: bridge
        name: ${PROJECT_NAME}_network